export const SERVICES = [
  { id: 'civic_works', title: 'Civic Works', description: 'Roads, lights, drainage, garbage', icon: '🏗️', img: '/assets/categories/civic/civic.png',
    options: [
      { id: 'road_repair', title: 'Road Repair', description: 'Potholes / damaged road', img: '/assets/categories/civic/road repair.png' },
      { id: 'street_light', title: 'Street Light', description: 'Light not working', img: '/assets/categories/civic/street light.png' },
      { id: 'drainage', title: 'Drainage', description: 'Blocked / overflow', img: '/assets/categories/civic/drainage.png' },
      { id: 'power_issue', title: 'Power Issue', description: 'Outage / fluctuation', img: '/assets/categories/civic/powercut.png' },
      { id: 'garbage_issue', title: 'Garbage Issue', description: 'Waste not collected', img: '/assets/categories/civic/garbage.png' },
    ],
  },
  { id: 'revenue', title: 'Revenue', description: 'Certificates, patta, relief', icon: '📋', img: '/assets/categories/revenue/revenue.png',
    options: [
      { id: 'income_certificate', title: 'Income Certificate Issue', description: 'Apply / pending', img: '/assets/categories/revenue/income certificate.png' },
      { id: 'patta_issue', title: 'Patta Issue', description: 'Land patta', img: '/assets/categories/revenue/patta.png' },
      { id: 'disaster_relief', title: 'Disaster Relief', description: 'Relief request', img: '/assets/categories/revenue/diaster.png' },
      { id: 'death_birth_certificate', title: 'Death / Birth Certificate', description: 'Issue / correction', img: '/assets/categories/revenue/death & birth certificate.png' },
    ],
  },
  { id: 'health', title: 'Health', description: 'PHC, vaccination, ambulance', icon: '🏥', img: '/assets/categories/health/health.png',
    options: [
      { id: 'new_phc', title: 'New PHC', description: 'Request a new PHC', img: '/assets/categories/health/phc.png' },
      { id: 'vaccination_camp', title: 'Vaccination Camp Request', description: 'Request a camp', img: '/assets/categories/health/vaccination.png' },
      { id: 'ambulance_not_responding', title: 'Ambulance Not Responding', description: 'Emergency response issue', img: '/assets/categories/health/ambulance.png' },
    ],
  },
  { id: 'education', title: 'Education', description: 'Schools, mid-day meals, sports', icon: '📚', img: '/assets/categories/education/education.png',
    options: [
      { id: 'school_building_disrepair', title: 'School Building in Disrepair', description: 'Building issue', img: '/assets/categories/education/school derepair.png' },
      { id: 'mid_day_meal_issue', title: 'Mid-day Meal Issue', description: 'Quality / supply', img: '/assets/categories/education/mid-way meal.png' },
      { id: 'sports_infra_request', title: 'Sports Infrastructure Request', description: 'Equipment / ground', img: '/assets/categories/education/sports infrastucture.png' },
    ],
  },
  { id: 'ration', title: 'Ration', description: 'Ration card, pension, FPS', icon: '🍚', img: '/assets/categories/ration/ration.png',
    options: [
      { id: 'new_ration_card', title: 'New Ration Card', description: 'Apply for new card', img: '/assets/categories/ration/ration card.png' },
      { id: 'pension_not_received', title: 'Pension Not Received', description: 'Missing pension', img: '/assets/categories/ration/pension.png' },
      { id: 'rice_not_at_fps', title: 'Rice Not at FPS', description: 'Stock issue at FPS', img: '/assets/categories/ration/FPS.png' },
      { id: 'update_card', title: 'Update Card', description: 'Add / remove member', img: '/assets/categories/ration/update ration card.png' },
      { id: 'sc_st_welfare_not_received', title: 'SC/ST Welfare Not Received', description: 'Welfare issue', img: '/assets/categories/ration/sc st welfare.png' },
      { id: 'anganwadi_issue', title: 'Anganwadi Issue', description: 'Anganwadi service', img: '/assets/categories/education/mid-way meal.png' },
    ],
  },
  { id: 'agriculture', title: 'Agriculture', description: 'Insurance, loans, subsidies', icon: '🌾', img: '/assets/categories/agriculture/agriculture.png',
    options: [
      { id: 'crop_insurance_claim', title: 'Crop Insurance Claim', description: 'Claim status', img: '/assets/categories/agriculture/crop insurance.png' },
      { id: 'kissan_loan_issue', title: 'Kissan Loan Issue', description: 'Loan issue', img: '/assets/categories/agriculture/kisan.png' },
      { id: 'seeds_fertilizers_subsidy', title: 'Seeds / Fertilizers Subsidy', description: 'Subsidy issue', img: '/assets/categories/agriculture/seeds.png' },
      { id: 'equipment_subsidy', title: 'Equipment Subsidy', description: 'Equipment subsidy', img: '/assets/categories/agriculture/equipment subsity.png' },
      { id: 'fisherman_welfare', title: 'Fisherman Welfare', description: 'Welfare scheme', img: '/assets/categories/agriculture/fishermen.png' },
      { id: 'flood_compensation', title: 'Flood Compensation', description: 'Compensation request', img: '/assets/categories/agriculture/flood.png' },
    ],
  },
  { id: 'law_order', title: 'Law & Order', description: 'FIR, legal aid, safety', icon: '⚖️', img: '/assets/categories/law and order/law and order.png',
    options: [
      { id: 'fir_not_filed', title: 'FIR Not Filed', description: 'Police did not file FIR', img: '/assets/categories/law and order/fir.png' },
      { id: 'legal_aid_request', title: 'Legal Aid Request', description: 'Free legal aid', img: '/assets/categories/law and order/legal aid request.png' },
      { id: 'eve_teasing', title: 'Eve-Teasing', description: 'Harassment complaint', img: '/assets/categories/law and order/eve teasing.png' },
      { id: 'illegal_dump', title: 'Illegal Dump', description: 'Illegal dumping', img: '/assets/categories/law and order/illegal dump.png' },
    ],
  },
  { id: 'employment', title: 'Employment', description: 'Skills, EPF, MSME', icon: '💼', img: '/assets/categories/employement/employment.png',
    options: [
      { id: 'job', title: 'Job', description: 'Job opportunities / placement', img: '/assets/categories/employement/employment.png' },
      { id: 'skill_training', title: 'Skill Training', description: 'Training programs', img: '/assets/categories/employement/skill training.png' },
      { id: 'self_employment', title: 'Self Employment', description: 'Self-employment scheme', img: '/assets/categories/employement/self empled.png' },
      { id: 'epf_issue', title: 'EPF Issue', description: 'Provident fund issue', img: '/assets/categories/employement/epf esi.png' },
      { id: 'msme_loan', title: 'MSME Loan', description: 'MSME loan support', img: '/assets/categories/employement/MSME.png' },
    ],
  },
  { id: 'personal_assistance', title: 'Personal Assistance', description: 'Old age, marriage, disputes', icon: '🤝', img: '/assets/categories/health/health.png',
    options: [
      { id: 'old_age_care', title: 'Old Age Care', description: 'Senior citizen care', img: '/assets/categories/ration/pension.png' },
      { id: 'marriage_assistance_scheme', title: 'Marriage Assistance Scheme', description: 'Marriage scheme', img: '/assets/categories/ration/sc st welfare.png' },
      { id: 'fire_accident_relief', title: 'Fire Accident Relief', description: 'Relief after fire', img: '/assets/categories/revenue/diaster.png' },
      { id: 'recommendation_letter', title: 'Recommendation Letter', description: 'Request letter', img: '/assets/categories/social/gmsil.png' },
      { id: 'property_dispute_mediation', title: 'Property Dispute Mediation', description: 'Mediation request', img: '/assets/categories/law and order/legal aid request.png' },
    ],
  },
]
