export const SERVICES = [
  { id: 'civic_works', title: 'Civic Works', description: 'Roads, lights, drainage, garbage', icon: '🏗️',
    options: [
      { id: 'road_repair', title: 'Road Repair', description: 'Potholes / damaged road' },
      { id: 'street_light', title: 'Street Light', description: 'Light not working' },
      { id: 'drainage', title: 'Drainage', description: 'Blocked / overflow' },
      { id: 'power_issue', title: 'Power Issue', description: 'Outage / fluctuation' },
      { id: 'garbage_issue', title: 'Garbage Issue', description: 'Waste not collected' },
    ],
  },
  { id: 'revenue', title: 'Revenue', description: 'Certificates, patta, relief', icon: '📋',
    options: [
      { id: 'income_certificate', title: 'Income Certificate Issue', description: 'Apply / pending' },
      { id: 'patta_issue', title: 'Patta Issue', description: 'Land patta' },
      { id: 'disaster_relief', title: 'Disaster Relief', description: 'Relief request' },
      { id: 'death_birth_certificate', title: 'Death / Birth Certificate', description: 'Issue / correction' },
    ],
  },
  { id: 'health', title: 'Health', description: 'PHC, vaccination, ambulance', icon: '🏥',
    options: [
      { id: 'new_phc', title: 'New PHC', description: 'Request a new PHC' },
      { id: 'vaccination_camp', title: 'Vaccination Camp Request', description: 'Request a camp' },
      { id: 'ambulance_not_responding', title: 'Ambulance Not Responding', description: 'Emergency response issue' },
    ],
  },
  { id: 'education', title: 'Education', description: 'Schools, mid-day meals, sports', icon: '📚',
    options: [
      { id: 'school_building_disrepair', title: 'School Building in Disrepair', description: 'Building issue' },
      { id: 'mid_day_meal_issue', title: 'Mid-day Meal Issue', description: 'Quality / supply' },
      { id: 'sports_infra_request', title: 'Sports Infrastructure Request', description: 'Equipment / ground' },
    ],
  },
  { id: 'ration', title: 'Ration', description: 'Ration card, pension, FPS', icon: '🍚',
    options: [
      { id: 'new_ration_card', title: 'New Ration Card', description: 'Apply for new card' },
      { id: 'pension_not_received', title: 'Pension Not Received', description: 'Missing pension' },
      { id: 'rice_not_at_fps', title: 'Rice Not at FPS', description: 'Stock issue at FPS' },
      { id: 'update_card', title: 'Update Card', description: 'Add / remove member' },
      { id: 'sc_st_welfare_not_received', title: 'SC/ST Welfare Not Received', description: 'Welfare issue' },
      { id: 'anganwadi_issue', title: 'Anganwadi Issue', description: 'Anganwadi service' },
    ],
  },
  { id: 'agriculture', title: 'Agriculture', description: 'Insurance, loans, subsidies', icon: '🌾',
    options: [
      { id: 'crop_insurance_claim', title: 'Crop Insurance Claim', description: 'Claim status' },
      { id: 'kissan_loan_issue', title: 'Kissan Loan Issue', description: 'Loan issue' },
      { id: 'seeds_fertilizers_subsidy', title: 'Seeds / Fertilizers Subsidy', description: 'Subsidy issue' },
      { id: 'equipment_subsidy', title: 'Equipment Subsidy', description: 'Equipment subsidy' },
      { id: 'fisherman_welfare', title: 'Fisherman Welfare', description: 'Welfare scheme' },
      { id: 'flood_compensation', title: 'Flood Compensation', description: 'Compensation request' },
    ],
  },
  { id: 'law_order', title: 'Law & Order', description: 'FIR, legal aid, safety', icon: '⚖️',
    options: [
      { id: 'fir_not_filed', title: 'FIR Not Filed', description: 'Police did not file FIR' },
      { id: 'legal_aid_request', title: 'Legal Aid Request', description: 'Free legal aid' },
      { id: 'eve_teasing', title: 'Eve-Teasing', description: 'Harassment complaint' },
      { id: 'illegal_dump', title: 'Illegal Dump', description: 'Illegal dumping' },
    ],
  },
  { id: 'employment', title: 'Employment', description: 'Skills, EPF, MSME', icon: '💼',
    options: [
      { id: 'job', title: 'Job', description: 'Job opportunities / placement' },
      { id: 'skill_training', title: 'Skill Training', description: 'Training programs' },
      { id: 'self_employment', title: 'Self Employment', description: 'Self-employment scheme' },
      { id: 'epf_issue', title: 'EPF Issue', description: 'Provident fund issue' },
      { id: 'msme_loan', title: 'MSME Loan', description: 'MSME loan support' },
    ],
  },
  { id: 'personal_assistance', title: 'Personal Assistance', description: 'Old age, marriage, disputes', icon: '🤝',
    options: [
      { id: 'old_age_care', title: 'Old Age Care', description: 'Senior citizen care' },
      { id: 'marriage_assistance_scheme', title: 'Marriage Assistance Scheme', description: 'Marriage scheme' },
      { id: 'fire_accident_relief', title: 'Fire Accident Relief', description: 'Relief after fire' },
      { id: 'recommendation_letter', title: 'Recommendation Letter', description: 'Request letter' },
      { id: 'property_dispute_mediation', title: 'Property Dispute Mediation', description: 'Mediation request' },
    ],
  },
]
